version: '3'
services:
  postgres-db:
    image: postgres:12
    restart: always
    ports:
      - 5433:5432
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
